"""make categoria_produto nullable

Revision ID: 828900b17b7b
Revises: 001
Create Date: 2026-04-13 19:57:25.444163

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '828900b17b7b'
down_revision: Union[str, None] = '001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('produtos') as batch_op:
        batch_op.alter_column('categoria_produto',
                   existing_type=sa.VARCHAR(length=100),
                   nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('produtos') as batch_op:
        batch_op.alter_column('categoria_produto',
                   existing_type=sa.VARCHAR(length=100),
                   nullable=False)
    # ### end Alembic commands ###
