"""Shared enums used across models and schemas."""
from enum import Enum as PyEnum

class OrderStatus(str, PyEnum):
    criado = "criado"
    aprovado = "aprovado"
    faturado = "faturado"
    em_processamento = "em processamento"
    enviado = "enviado"
    entregue = "entregue"
    cancelado = "cancelado"
    indisponivel = "indisponível"

class OnTimeDelivery(str, PyEnum):
    sim = "Sim"
    nao = "Não"
    nao_entregue = "Não Entregue"

class BrazilState(str, PyEnum):
    AC = "AC"
    AL = "AL"
    AM = "AM"
    AP = "AP"
    BA = "BA"
    CE = "CE"
    DF = "DF"
    ES = "ES"
    GO = "GO"
    MA = "MA"
    MG = "MG"
    MS = "MS"
    MT = "MT"
    PA = "PA"
    PB = "PB"
    PE = "PE"
    PI = "PI"
    PR = "PR"
    RJ = "RJ"
    RN = "RN"
    RO = "RO"
    RR = "RR"
    RS = "RS"
    SC = "SC"
    SE = "SE"
    SP = "SP"
    TO = "TO"